[project]
name = "t5-env"
version = "0.1.0"
dependencies = [
    "transformers", # This will be pulled from the git source defined in root
    "accelerate>=1.12.0",
    "pandas>=2.3.3",
    "scipy>=1.16.3",
    "statsmodels>=0.14.6",
]
requires-python = ">=3.12"
